// <auto-generated />
using System;
using LinkShortener;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinkShortener.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190908115404_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LinkShortener.Models.Link", b =>
                {
                    b.Property<string>("ShortUrl")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Counter");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Url");

                    b.HasKey("ShortUrl");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
